config/routes.rb
FinanceHw::Application.routes.draw do

  root to: 'finance#index'
  match '/finance', to: 'finance#index'  
  match '/about', to: 'finance#about'     
  match '/result', to: 'finance#result'  
  match '/:symbol', to: 'finance#result'  
 

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/finance_controller.rb
class FinanceController < ApplicationController

  def index
  end

  def about
  end

  def result
    @symbol = params[:symbol].upcase
    if @symbol.empty?
      flash[:error] = "Symbol can't be blank. Type it in."
      render :index
    else
      @quote = YahooFinance::get_quotes(YahooFinance::StandardQuote, @symbol)[@symbol]
      if @quote.lastTrade == 0
        flash[:error] = "Invalid symbol. Please type in a correct one."
        render :index
      end
    end 
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/finance/404.html.erb
<div class="container">

<p>SORRY! Page not found</p>

</div>

app/views/finance/about.html.erb
<div class="container">
  <h2>About this app</h2>
  <p>This is a web app by Accrue Inc. Use this tool to look up real-time stock data, and make projections.</p>
</div>

app/views/finance/index.html.erb
  <div class="hero-unit">
  <% flash.each do |key, value| %>
    <p class="alert alert-error"><%= key %> <%= value %></p>
  <% end %>

  <h1>Stock Market Analysis</h1>
  <h3>Search by Company Symbol to Look Up Quotes</h3>
  <form action="/result" method="get">
    <input type="text" name="symbol" class="field_input" placeholder="Enter Stock Symbol">
    <button class="button btn btn-success">Search</button>
  </form>
</div>



 
<!--         <div class="span12">
 -->          
          <div class="row-fluid">
            <div class="span4">
              <h1>Probability</h1>
              <p> Stock </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h1>Projection</h1>
              <p>Stock. </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h1>Analysis</h1>
              <p>Stock </p>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->

app/views/finance/result.html.erb
<div class="container-fluid">
      <div class="row-fluid">
        <div class="span3">
          <div class="well sidebar-nav">
            <ul class="nav nav-list">
              <li class="nav-header">Trending Stocks</li>
<!--               <li class="active"><a href="#">Web Applications</a></li>
 -->              <li><a href="#">Google Inc.</a></li>
              <li><a href="#">Apple Inc.</a></li>
              <li><a href="#">Amazon Inc.</a></li>
              <li><a href="#">Microsoft</a></li>
              <li class="nav-header">Bidu Inc.</li>
              <li><a href="#">Chipotle</a></li>
              <li><a href="#">Walmart</a></li>
               <li><a href="#">Starbucks Inc.</a></li>
              <li><a href="#">Yahoo Inc.</a></li>
              <li><a href="#">Ebay Inc.</a></li>
              <li class="nav-header">Other Feature</li>
              <li><a href="#">Accrue Stock of the Day</a></li>
              <li><a href="#">News and Trends</a></li>
              <li><a href="#">Market Analysis</a></li>
  
             
              <!-- 
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li> -->
             <!--  <li class="nav-header">Consulting</li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li>
              <li><a href="#">Link</a></li> -->
            </ul>
          </div><!--/.well -->
        </div><!--/span-->



<div class="hero-unit span9">
          
          <div class="row-fluid">
            <div class="span4">
              <h2>Accrue Score</h2>
              <h3> 55/100 (55%) </h3>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Month's Probability</h2>
              <h3>67/100 (67%) </h3>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
            <div class="span4">
              <h2>Today's probability</h2>
              <h3>77/100 (77%) </h3>
              <p><a class="btn" href="#">View details &raquo;</a></p>
            </div><!--/span-->
          </div><!--/row-->


<div class="hero-unit">
      <div class="row-fluid">
<%= link_to "<<Back", :back %>   
  <h2>Stock Quote for <%= @quote.name %></h2>
  <ul class="data">
  <li><span class="sub_headings">Date:</span> <%= @quote.date %></li>
  <li><span class="sub_headings">Time:</span>  <%= @quote.time %></li>
  <li><span class="sub_headings">Day High:</span>  <%= @quote.dayHigh %></li>
  <li><span class="sub_headings">Day Low:</span>  <%= @quote.dayLow %></li>
  <li><span class="sub_headings">Last Trade:</span>  <%= @quote.lastTrade %></li>
  <li><span class="sub_headings">Symbol:</span>  <%= @quote.symbol %></li>
  </ul>
  


</div> 
</div> 



 

app/views/layouts/_footer.html.erb
<div class="container">
  

  <footer class="footer">
    <small>Accrue | Apps for Insight</small>
    <nav>
      <ul>
        <li><%= link_to "Home", root_path %></li> 
        <li><%= link_to "About", about_path %></li>     
      </ul>
    </nav>
  </footer>
</div>

app/views/layouts/_header.html.erb
<!-- <header class="navbar navbar-fixed-top navbar-inverse">
  <div class="navbar-inner">
    <div class="container">
      <%= link_to "Stock Quote", root_path, id: "logo" %>
      <nav>
        <ul class="nav pull-left pull-up">
        <li>
              <a class="brand" href=""> <img alt="Accrue" src="accrue line logo.png" style="height:70px"> 
             </a>
             </li>
         </ul>    

        <ul class="nav pull-right">
          <li>
            <form navbar-search action="/result" method="get"> 
              <input type="text" name="symbol" class="field_input" placeholder="Enter Stock Symbol">
              <button class="button btn btn-success">Search</button>
            </form> 
          </li>
          <li><%= link_to "Home", root_path %></li>
          <li><%= link_to "About", about_path %></li>    
          <li><%= link_to "Contact", about_path %></li>    
        </ul>
      </nav>
    </div>
  </div> 
 -->
    <!-- Le styles -->
    <link href="../assets/css/bootstrap.css" rel="stylesheet">
    <style type="text/css">
      body {
        padding-top: 60px;
        padding-bottom: 40px;
      }
      .sidebar-nav {
        padding: 69px 0;
      }

      @media (max-width: 980px) {
        /* Enable use of floated navbar text */
        .navbar-text.pull-right {
          float: none;
          padding-left: 5px;
          padding-right: 5px;
        }
      }
    </style>
    <link href="../assets/css/bootstrap-responsive.css" rel="stylesheet">


    <div class="navbar navbar-inverse navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container-fluid">
          <button type="button" class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
                     
     </div>
  
          <div class="nav-collapse collapse">
            <p class="navbar-text pull-right">
            </p>
            <li>
              <a class="brand" href=""> <img alt="Accrue" src="Accrue line logo.png" style="height:70px"> 
             </a>
             </li>
            <ul >
              <li class="nav pull-right">
           <form navbar-search action="/result" method="get"> 
              <input type="text" name="symbol" class="field_input" placeholder="Enter Stock Symbol">
              <button class="button btn btn-success">Search</button>
            </form> 
            </li>
            <ul class="nav pull-right">
              <li ><%= link_to "Home", root_path %></li>
              <li><%= link_to "About", about_path %></li>    
              <li><a href="#contact">Contact</a></li>
            </ul>
          </ul>
           
          </div>
        </div>
      </div>
    </div>
</header>
 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Accrue</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body> 
<%= render 'layouts/header' %>
<%= yield %>
<%= render 'layouts/footer' %>
</body>
</html>